// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJhrJy9J9KUQELur0Ga7s1l9-lW8qOauA',
    appId: '1:776881885763:web:94eae6ec7d0968ac233af6',
    messagingSenderId: '776881885763',
    projectId: 'forest-invent',
    authDomain: 'forest-invent.firebaseapp.com',
    storageBucket: 'forest-invent.appspot.com',
    measurementId: 'G-E7J38S0VTH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiXX4lnhhsRf2W3KjjGJ0BGfM8wpJI-7Q',
    appId: '1:776881885763:android:f5e2c0c5800c10a2233af6',
    messagingSenderId: '776881885763',
    projectId: 'forest-invent',
    storageBucket: 'forest-invent.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOY1LWAaT6PE8lRwL7hSfTPG62R_1QdUM',
    appId: '1:776881885763:ios:4477787ef0bea7cc233af6',
    messagingSenderId: '776881885763',
    projectId: 'forest-invent',
    storageBucket: 'forest-invent.appspot.com',
    androidClientId: '776881885763-63nsklifv7hus9h00j7ij39437nacgck.apps.googleusercontent.com',
    iosClientId: '776881885763-b75r7nps7fslikhj79b3hmbkca6o3pr7.apps.googleusercontent.com',
    iosBundleId: 'com.syncfusion.flutterExamples',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOY1LWAaT6PE8lRwL7hSfTPG62R_1QdUM',
    appId: '1:776881885763:ios:4477787ef0bea7cc233af6',
    messagingSenderId: '776881885763',
    projectId: 'forest-invent',
    storageBucket: 'forest-invent.appspot.com',
    androidClientId: '776881885763-63nsklifv7hus9h00j7ij39437nacgck.apps.googleusercontent.com',
    iosClientId: '776881885763-b75r7nps7fslikhj79b3hmbkca6o3pr7.apps.googleusercontent.com',
    iosBundleId: 'com.syncfusion.flutterExamples',
  );
}
